name: Deploy Discord Bot

on:
  push:
    branches:
      - main
      - production

jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'Merge pull request')
    runs-on: [self-hosted, X64, AtlasOS, Linux]
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create logs directory
        run: mkdir -p logs
        
      - name: Create .env file
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        
      - name: Start or restart PM2 process
        run: |
          # Check if PM2 is installed globally; if not, install it
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi
          
          # Create PM2 config file if it doesn't exist
          if [ ! -f "discord-bot.json" ]; then
            cat > discord-bot.json << EOF
            {
              "apps": [
                {
                  "name": "veka-discord-bot",
                  "script": "main.py",
                  "interpreter": "python",
                  "instances": 1,
                  "autorestart": true,
                  "watch": false,
                  "max_memory_restart": "1G",
                  "env": {
                    "NODE_ENV": "production"
                  }
                }
              ]
            }
            EOF
          fi
          
          # Use a direct check for process info instead of grep on pm2 list
          if pm2 info veka-discord-bot > /dev/null 2>&1; then
            pm2 restart veka-discord-bot --update-env
          else
            pm2 start discord-bot.json --update-env
          fi
          
          # Save the PM2 process list
          pm2 save
        shell: bash

      - name: Health check
        shell: bash
        run: |
          # Wait for the bot to start
          sleep 10
          
          # Check if the bot process is running
          if pm2 info veka-discord-bot | grep -q "online"; then
            echo "Health check passed - Bot is running"
          else
            echo "Health check failed - Bot is not running"
            exit 1
          fi
          
          # Check logs for successful connection
          if grep -q "has connected to Discord" logs/bot.log; then
            echo "Health check passed - Bot connected to Discord"
          else
            echo "Health check failed - Bot did not connect to Discord"
            exit 1
          fi 